### ISSUE TITLE
configuration: store verification key in configuration file

### ISSUE THREAD

**Issue by achille-roussel** [stealthrocket/dispatch#7]
When rolling out a new verification key, we print the new key to the console but the user is responsible for adding it to its code or environment.

We could simplify this process by storing the public key in the configuration file. The `dispatch run` command could then read it from the file and automatically set it as an environment variable.

Relates to #6

**Comment by chriso** [comment]
Using a verification key in `dispatch run` serves no purpose, since the CLI pulls requests from an authenticated API endpoint.

We could fetch or generate a verification key in the CLI, and set `DISPATCH_VERIFICATION_KEY` in `dispatch run`, however this only adds footguns for the user. If they roll-out a new verification key through the UI, or using the CLI on a different machine, the cached verification key in the config will no longer work.

Instead of caching a verification key, and using it in `dispatch run`, I'll instead hide the warning about a lack of verification key in the SDK: https://github.com/stealthrocket/dispatch-py/pull/152.
